### ISSUE TITLE
Initialization behavior differs from 3.11 due to __init__

### ISSUE THREAD

**Issue by KevinMGranger** [agronholm/exceptiongroup#46]
Due to `__init__` receiving the same arguments as `__new__`, a custom signature can break exception formatting. Additionally, the same signature can have unexpected behavior if arguments are modified before passing them to `ExceptionGroup.__new__`.

I'm not sure how cpython implements this, but it does work differently.

Here's the behavior with the [official example in the 3.11 reference](https://docs.python.org/3.11/library/exceptions.html#:~:text=class-,Errors,-(ExceptionGroup)%3A):
<details><summary>errors.py</summary>

```python
from exceptiongroup import ExceptionGroup, print_exception


class Errors(ExceptionGroup):
    """
    Example from the stdlib docs:
    https://docs.python.org/3.11/library/exceptions.html#ExceptionGroup:~:text=message%20from%20it.-,class,-Errors(ExceptionGroup
    """

    def __new__(cls, errors, exit_code):
        self = super().__new__(Errors, f"exit code: {exit_code}", errors)
        self.exit_code = exit_code
        return self

    def derive(self, excs):
        return Errors(excs, self.exit_code)


print_exception(Errors([Exception("uhoh")], 2))
```
</details>

```console
$ python3.11 errors.py 
  | Errors: exit code: 2 (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception: uhoh
    +------------------------------------
$ python3.9 errors.py
Traceback (most recent call last):
  File "/Users/kevin/code/python-exrg/errors.py", line 19, in <module>
    print_exception(Errors([Exception("uhoh")], 2))
  File "/opt/homebrew/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/kevin/Library/Python/3.9/lib/python/site-packages/exceptiongroup/_formatting.py", line 402, in print_exception
    for line in PatchedTracebackException(
  File "/Users/kevin/Library/Python/3.9/lib/python/site-packages/exceptiongroup/_formatting.py", line 186, in __init__
    for exc in e.exceptions:
  File "/Users/kevin/Library/Python/3.9/lib/python/site-packages/exceptiongroup/_exceptions.py", line 98, in exceptions
    return tuple(self._exceptions)
TypeError: 'int' object is not iterable
```

The second issue with the same signature:
<details><summary>custom.py</summary>

```python
from exceptiongroup import ExceptionGroup, print_exception


class CustomMessage(ExceptionGroup):
    """
    Passing custom arguments to ExceptionGroup.__new__
    """

    def __new__(cls, msg: str, errors):
        count = f"there were {len(errors)} errors!"
        if msg:
            msg += f", {count}"
        else:
            msg = count

        return super().__new__(CustomMessage, msg, errors)


print_exception(CustomMessage("Oh no", [Exception("uhoh")]))
```
</details>

```console
$ python3.11 custom.py 
  | CustomMessage: Oh no, there were 1 errors! (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception: uhoh
    +------------------------------------
$ python3.9 custom.py
  | CustomMessage: Oh no (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception: uhoh
    +------------------------------------
```
(note the message next to `CustomMessage`)

**Comment by KevinMGranger** [comment]
I have a workaround for now. It's untested for various args / kwargs, but solves the TypeError and incorrect message.

```python
class Errors:
    def __new__(cls, errors, exit_code):
        message = "something"
        self = super().__new__(Errors, message, errors)
        self._message = message
        self.exit_code = exit_code

   def __init__(self, errors, exit_code, *args, **kwargs):
        super().__init__(self._message, errors)
```

**Comment by agronholm** [comment]
If you'd like to fix this in a PR, I'm willing to review it.

**Comment by KevinMGranger** [comment]
I'd like to take a swing at it! But first, I need to do further testing to get the right behavior with *args, **kwargs, multiple inheritance, etc.

**Comment by agronholm** [comment]
Would you like to review my PR?
