### ISSUE TITLE
bare raise in catch behaves differently to bare raise in native except*

### ISSUE THREAD

**Issue by graingert** [agronholm/exceptiongroup#70]
with the backport:

```python
import sys
import exceptiongroup


def raise_exc():
    raise ExceptionGroup("bad", [ValueError(), ValueError(), TypeError()])

def handle(eg):
    raise

def noop(*args, **kwargs):
    pass

with exceptiongroup.catch({ValueError: handle, TypeError: noop}):
    raise_exc()
```

I get:

```pytb
  + Exception Group Traceback (most recent call last):
  |   File "/home/graingert/.virtualenvs/testing311/lib/python3.11/site-packages/exceptiongroup/_catch.py", line 52, in handle_exception
  |     handler(matched)
  |   File "/home/graingert/projects/dask/backport.py", line 15, in <module>
  |     raise_exc()
  |   File "/home/graingert/projects/dask/backport.py", line 6, in raise_exc
  |     raise ExceptionGroup("bad", [ValueError(), ValueError(), TypeError()])
  | ExceptionGroup: bad (3 sub-exceptions)
  +-+---------------- 1 ----------------
    | ValueError
    +---------------- 2 ----------------
    | ValueError
    +---------------- 3 ----------------
    | TypeError
    +------------------------------------
```

with the native code:

```python
import sys
import exceptiongroup


def raise_exc():
    raise ExceptionGroup("bad", [ValueError(), ValueError(), TypeError()])

try:
    raise_exc()
except* ValueError as eg:
    raise
except* TypeError:
    pass
```

I get:

```pytb
  + Exception Group Traceback (most recent call last):
  |   File "/home/graingert/projects/dask/native.py", line 9, in <module>
  |     raise_exc()
  |   File "/home/graingert/projects/dask/native.py", line 6, in raise_exc
  |     raise ExceptionGroup("bad", [ValueError(), ValueError(), TypeError()])
  | ExceptionGroup: bad (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | ValueError
    +---------------- 2 ----------------
    | ValueError
    +------------------------------------
```

**Comment by agronholm** [comment]
This is caused by the original exception present in wherever `sys.exc_info()` gets the exception info from, as that's the exception in flight that `raise` re-raises. The only way to fix this is to raise the split exception group ourselves, letting the callback handle that then.
